/* Writes one static HTML file per route into dist/, each with its own <head>
 * and a fully server-rendered <body>.
 *
 * Why no headless browser: an earlier version drove Playwright, which needs a
 * Chromium binary the Vercel build image does not have — so it silently
 * skipped and every deploy shipped a bare SPA. It also rendered only "/" and
 * wrote it to dist/index.html, meaning /contact and /publications were served
 * the home page's metadata.
 *
 * The <head> of every route comes from src/seo/meta.ts — the same module
 * <Seo /> uses at runtime — so link unfurlers (LinkedIn, X, WhatsApp, Slack)
 * see the right title, description and JSON-LD without executing JavaScript.
 *
 * The <body> comes from src/entry-server.tsx, which renders <App> with
 * react-dom/server's renderToStaticMarkup. This used to be left empty on the
 * theory that "Googlebot executes JS and indexes it" — in practice, Search
 * Console reported every route beyond the homepage as "Discovered — currently
 * not indexed": Google saw an empty <div id="root"></div>, no text, no links,
 * and deprioritized coming back to render it. Real markup here means a
 * crawler's very first fetch already has the content.
 *
 * The client still does a plain createRoot().render() in main.tsx, not
 * hydrateRoot — so this static markup is discarded and replaced the moment
 * React mounts. That is deliberate: it means a component that behaves
 * differently with no DOM (Reveal starts "shown" because
 * IntersectionObserver doesn't exist in Node, for instance) can never produce
 * a hydration-mismatch error. The only cost is a brief flash before the
 * interactive app takes over, the same trade-off most static blogs make.
 *
 * This script fails the build on error instead of skipping quietly.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { build } from 'vite';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');
const tmpMeta = path.join(root, 'node_modules', '.tmp', 'prerender-meta');
const tmpServer = path.join(root, 'node_modules', '.tmp', 'prerender-server');

const START = '<!-- seo:start';
const END = '<!-- seo:end -->';

const die = (msg) => {
  console.error(`[prerender] ${msg}`);
  process.exit(1);
};

const escapeAttr = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/* `</script>` inside JSON-LD would close the tag early */
const jsonLdSafe = (data) => JSON.stringify(data).replace(/</g, '\\u003c');

function headBlock(meta, image, { indexable = true } = {}) {
  const tag = (n, v) => `    <meta name="${n}" content="${escapeAttr(v)}" />`;
  const prop = (p, v) => `    <meta property="${p}" content="${escapeAttr(v)}" />`;
  const ld = (id, data) =>
    data ? `    <script id="${id}" type="application/ld+json">${jsonLdSafe(data)}</script>` : null;

  return [
    `<!-- seo:start — generated by scripts/prerender.mjs, do not hand-edit -->`,
    `    <title>${escapeAttr(meta.title)}</title>`,
    tag('description', meta.description),
    tag('keywords', meta.keywords),
    /* an error page claims no canonical URL and offers no alternates */
    ...(indexable
      ? [
          `    <link rel="canonical" href="${escapeAttr(meta.url)}" />`,
          ...meta.alternates.map(
            ({ hreflang, href }) => `    <link rel="alternate" hreflang="${hreflang}" href="${escapeAttr(href)}" />`,
          ),
        ]
      : []),
    ``,
    prop('og:type', 'website'),
    prop('og:locale', meta.ogLocale),
    prop('og:locale:alternate', meta.ogLocaleAlternate),
    prop('og:site_name', meta.siteName),
    prop('og:title', meta.title),
    prop('og:description', meta.description),
    prop('og:url', meta.url),
    prop('og:image', image),
    prop('og:image:width', '1200'),
    prop('og:image:height', '630'),
    prop('og:image:alt', meta.title),
    prop('og:image:type', 'image/jpeg'),
    ``,
    tag('twitter:card', 'summary_large_image'),
    tag('twitter:site', '@SeynudeD'),
    tag('twitter:creator', '@SeynudeD'),
    tag('twitter:title', meta.title),
    tag('twitter:description', meta.description),
    tag('twitter:image', image),
    tag('twitter:image:alt', meta.title),
    ``,
    ld('person-jsonld', meta.jsonLd.person),
    ld('website-jsonld', meta.jsonLd.website),
    ld('breadcrumb-jsonld', meta.jsonLd.breadcrumb),
    ld('page-jsonld', meta.jsonLd.page),
    `    ${END}`,
  ]
    .filter((line) => line !== null)
    .join('\n');
}

async function loadMeta() {
  /* Compile the TS metadata module to plain ESM so this script can import it,
     keeping a single source of truth with the runtime <Seo /> component. */
  await build({
    configFile: false,
    logLevel: 'error',
    resolve: { alias: { '@': path.join(root, 'src') } },
    build: {
      ssr: path.join(root, 'src', 'seo', 'meta.ts'),
      outDir: tmpMeta,
      emptyOutDir: true,
      minify: false,
      rollupOptions: { output: { entryFileNames: 'meta.mjs' } },
    },
  });
  return import(pathToFileURL(path.join(tmpMeta, 'meta.mjs')).href);
}

async function loadRenderer() {
  /* Same trick, for the page tree itself. A separate output directory: both
     builds set emptyOutDir, and sharing one would let the second wipe out the
     first's output. */
  await build({
    configFile: false,
    logLevel: 'error',
    resolve: { alias: { '@': path.join(root, 'src') } },
    build: {
      ssr: path.join(root, 'src', 'entry-server.tsx'),
      outDir: tmpServer,
      emptyOutDir: true,
      minify: false,
      rollupOptions: { output: { entryFileNames: 'entry-server.mjs' } },
    },
  });
  return import(pathToFileURL(path.join(tmpServer, 'entry-server.mjs')).href);
}

async function run() {
  if (!fs.existsSync(path.join(dist, 'index.html'))) {
    die('dist/index.html missing — run `vite build` first.');
  }

  const template = fs.readFileSync(path.join(dist, 'index.html'), 'utf-8');
  const startAt = template.indexOf(START);
  const endAt = template.indexOf(END);
  if (startAt === -1 || endAt === -1 || endAt < startAt) {
    die(`SEO markers not found in dist/index.html — expected "${START}" … "${END}" (check index.html).`);
  }

  const {
    pageMeta,
    localePath,
    DEFAULT_LANG,
    PRERENDER_ROUTES,
    PRERENDER_LANGS,
    ROUTE_PRIORITY,
    DEFAULT_ROUTE_PRIORITY,
    SITE_URL,
  } = await loadMeta();
  const { renderPage } = await loadRenderer();
  const image = `${SITE_URL}/og-image.jpg`;

  const before = template.slice(0, startAt);
  const after = template.slice(endAt + END.length);
  if (!after.includes('<div id="root"></div>')) {
    die('<div id="root"></div> not found in dist/index.html — check index.html.');
  }

  const withBody = (html, bodyHtml) => html.replace('<div id="root"></div>', `<div id="root">${bodyHtml}</div>`);

  let written = 0;
  for (const lang of PRERENDER_LANGS) {
    for (const route of PRERENDER_ROUTES) {
      const meta = pageMeta(lang, route);
      const urlPath = localePath(lang, route);
      const bodyHtml = renderPage(urlPath);
      /* <html lang> sits outside the SEO block but still has to follow the
         language of the page being written */
      const html = withBody(before + headBlock(meta, image) + after, bodyHtml).replace(
        /<html lang="[^"]*"/,
        `<html lang="${lang}"`,
      );
      const outFile = urlPath === '/' ? path.join(dist, 'index.html') : path.join(dist, urlPath, 'index.html');
      fs.mkdirSync(path.dirname(outFile), { recursive: true });
      fs.writeFileSync(outFile, html, 'utf-8');
      written++;
    }
    console.log(`[prerender] ${lang}: ${PRERENDER_ROUTES.length} pages`);
  }

  /* 404.html — Vercel serves it with a real 404 status for anything that
     matched no route, instead of the soft 200 the SPA fallback produced.
     Rendered from the same unmatched path pageMeta already treats as 404, so
     the two can't disagree with each other. */
  const notFoundPath = '/__not-found__';
  const notFoundMeta = pageMeta(DEFAULT_LANG, notFoundPath);
  if (!notFoundMeta.notFound) die('pageMeta no longer flags unknown routes — 404.html would claim to be a real page.');
  const notFoundBody = renderPage(notFoundPath);
  const notFoundHtml = withBody(
    before +
      headBlock(
        { ...notFoundMeta, jsonLd: { ...notFoundMeta.jsonLd, breadcrumb: null } },
        image,
        { indexable: false },
      ) +
      after,
    notFoundBody,
  ).replace(/<meta name="robots" content="[^"]*"/, '<meta name="robots" content="noindex, follow"');
  fs.writeFileSync(path.join(dist, '404.html'), notFoundHtml, 'utf-8');

  /* The sitemap is generated from the same route list, so it can no longer
     drift from what is actually deployed. */
  const lastmod = new Date().toISOString().slice(0, 10);
  const urls = PRERENDER_LANGS.flatMap((lang) =>
    PRERENDER_ROUTES.map((route) => {
      const meta = pageMeta(lang, route);
      const { priority, changefreq } = ROUTE_PRIORITY[route] || DEFAULT_ROUTE_PRIORITY;
      const alts = meta.alternates
        .map(({ hreflang, href }) => `<xhtml:link rel="alternate" hreflang="${hreflang}" href="${href}"/>`)
        .join('');
      return `  <url><loc>${meta.url}</loc><lastmod>${lastmod}</lastmod><changefreq>${changefreq}</changefreq><priority>${priority}</priority>${alts}</url>`;
    }),
  );
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${urls.join('\n')}\n</urlset>\n`;
  fs.writeFileSync(path.join(dist, 'sitemap.xml'), sitemap, 'utf-8');

  console.log(`[prerender] ${written} pages + 404.html + sitemap.xml (${urls.length} urls)`);
}

run().catch((e) => die(e.stack || e.message));
